// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXkw8HlUjoZbpfYj8wxi2a_0hdtF1n-mk',
    appId: '1:536986300433:web:0d216194b2824898cd01b0',
    messagingSenderId: '536986300433',
    projectId: 'blood-donation-app-1ef5b',
    authDomain: 'blood-donation-app-1ef5b.firebaseapp.com',
    storageBucket: 'blood-donation-app-1ef5b.appspot.com',
    measurementId: 'G-H3ZSBMLB2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-rYmbjAxD0wB1kaqlfYzFUG4WUKKupIM',
    appId: '1:536986300433:android:a7713fadd1f2ebeacd01b0',
    messagingSenderId: '536986300433',
    projectId: 'blood-donation-app-1ef5b',
    storageBucket: 'blood-donation-app-1ef5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxqdUsOW1e8Avmq8mO-wiGEpDw0QcNxvQ',
    appId: '1:536986300433:ios:fcd9ea4e64064fd3cd01b0',
    messagingSenderId: '536986300433',
    projectId: 'blood-donation-app-1ef5b',
    storageBucket: 'blood-donation-app-1ef5b.appspot.com',
    iosClientId: '536986300433-a8t4df69ah111cnja0vf4p5fpvv7q96f.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodDonate',
  );
}
